---
- name: Create sydent user
  user:
    name: sydent
    state: present

- name: create folder
  file:
    name: "{{ matrix_sydent_home }}"
    owner: sydent
    group: sydent
    state: directory

- name: Install sqlite3
  apt:
    name: sqlite3=3.16.*
    default_release: jessie-backports
    state: present

- name: create log folder
  file:
    name: /var/log/sydent
    owner: sydent
    group: sydent
    state: directory

- name: Create virtualenv
  pip:
    name:
      - pip
      - setuptools
    virtualenv: "{{ matrix_sydent_home }}/env"
    virtualenv_python: python2.7
    extra_args: --upgrade
  become_user: sydent
  become: true

- name: Clone syndent
  git:
    repo: https://github.com/matrix-org/sydent
    dest: "{{ matrix_sydent_home }}/sydent"
    accept_hostkey: yes
    version: "{{ matrix_sydent_tag }}"
  become_user: sydent
  become: true
  register: clone_sydent

- name: Install Sydent
  pip:
    name: "{{ matrix_sydent_home }}/sydent"
    editable: true
    virtualenv: "{{ matrix_sydent_home}}/env"
    virtualenv_python: python2.7
  become_user: sydent
  become: true
  when: clone_sydent.changed
  tags:
    - skip_ansible_lint # skip should be handler check
  notify: "restart matrix-sydent"
