---
- name: Create sydent user
  user:
    name: sydent
    state: present

- name: create folder
  file:
    name: "{{ matrix_sydent_home }}"
    owner: sydent
    group: sydent
    state: directory

